# site settings

title: Diren Bharwani
description: Diren Bharwani's Portfolio & Blog
taglong: Software Engineer
# tagshort: Software Engineer
url: https://direnbharwani.github.io
permalink: pretty
repo: https://github.com/direnbharwani/direnbharwani.github.io

# author settings

author:
  name: Diren Bharwani
  email: diren.bharwani@gmail.com
# photo: /assets/jpg/photo.jpg

# social media links

social:
  # facebook: username
  github: direnbharwani
  # instagram: username
  linkedin: diren-bharwani
  # stackoverflow: 0000000/username
  # twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
